apiVersion: v1
kind: Service
metadata:
  name: release-guardian
  labels:
    app: release-guardian
spec:
  type: LoadBalancer
  selector:
    app: release-guardian
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
